// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package mysql

import (
	"database/sql"
	"time"
)

type Message struct {
	ID        string
	Content   string
	UserID    string
	RoomID    string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Room struct {
	ID        string
	Name      string
	UserID    string
	Type      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type User struct {
	ID        string
	Email     string
	FirstName string
	LastName  string
	Avatar    string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type UsersRoom struct {
	UserID string
	RoomID string
}
