// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package mysql

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (id, first_name, last_name, email, avatar)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Avatar    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Avatar,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, first_name, last_name, avatar, created_at, updated_at, deleted_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const searchUser = `-- name: SearchUser :many
SELECT id, email, first_name, last_name, avatar, created_at, updated_at, deleted_at 
FROM users u
WHERE u.email LIKE ?
AND NOT EXISTS (
	SELECT id, name, user_id, type, created_at, updated_at, deleted_at 
	FROM rooms r
	WHERE r.type = "PRIVATE"
	AND (
		SELECT COUNT(*)
		FROM users_rooms ur
		WHERE ur.room_id = r.id AND (ur.user_id = u.id OR ur.user_id = ?)
	) = 2
)
AND u.id != ?
`

type SearchUserParams struct {
	Email  string
	UserID string
	ID     string
}

func (q *Queries) SearchUser(ctx context.Context, arg SearchUserParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUser, arg.Email, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Avatar,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserNotInRoom = `-- name: SearchUserNotInRoom :many
SELECT id, email, first_name, last_name, avatar, created_at, updated_at, deleted_at 
FROM users u
WHERE u.id NOT IN (
	SELECT user_id
	FROM users_rooms ur 
	WHERE room_id = ?
)
AND u.email LIKE ?
`

type SearchUserNotInRoomParams struct {
	RoomID string
	Email  string
}

func (q *Queries) SearchUserNotInRoom(ctx context.Context, arg SearchUserNotInRoomParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUserNotInRoom, arg.RoomID, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Avatar,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users 
SET first_name = ?, last_name = ?, avatar = ?
WHERE id = ?
`

type UpdateUserParams struct {
	FirstName string
	LastName  string
	Avatar    string
	ID        string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Avatar,
		arg.ID,
	)
	return err
}
