// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user_room.sql

package mysql

import (
	"context"
)

const addUserToRoom = `-- name: AddUserToRoom :exec
INSERT INTO users_rooms (user_id, room_id)
VALUES (?, ?)
`

type AddUserToRoomParams struct {
	UserID string
	RoomID string
}

func (q *Queries) AddUserToRoom(ctx context.Context, arg AddUserToRoomParams) error {
	_, err := q.db.ExecContext(ctx, addUserToRoom, arg.UserID, arg.RoomID)
	return err
}

const removeUserFromRoom = `-- name: RemoveUserFromRoom :exec
DELETE FROM users_rooms 
WHERE user_id = ? AND room_id = ?
`

type RemoveUserFromRoomParams struct {
	UserID string
	RoomID string
}

func (q *Queries) RemoveUserFromRoom(ctx context.Context, arg RemoveUserFromRoomParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromRoom, arg.UserID, arg.RoomID)
	return err
}
